name: open_fda
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/devsdocs/open_fda

environment:
  sdk: ^3.1.2

dependencies:
  csv: ^5.0.2
  reusable_tools: ^1.0.14
  yaml: ^3.1.2
  yaml_magic: ^1.0.5

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
